# The following lines were added by compinstall

zstyle ':completion:*' menu select
zstyle :compinstall filename '/home/vagrant/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd
bindkey -v
# End of lines configured by zsh-newuser-install

# aliasi niga
alias config='/usr/bin/git --git-dir=$HOME/.myconf/ --work-tree=$HOME'
alias ls='ls -GFh'
alias dev='cd /srv/nerdwallet'
alias box='cd /Users/karlfrazier/dev-vagrant/vmware; vagrant ssh'
alias vagrant='cd /Users/karlfrazier/dev-vagrant/vmware; /usr/bin/vagrant $1'
alias update_zsh='cd ~/.zprezto; git pull; cd -; zsh'
alias identity='cd /srv/nerdwallet/identity.nerdwallet'

source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
