# The following lines were added by compinstall

zstyle ':completion:*' menu select
zstyle :compinstall filename '~/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd
bindkey -v
# End of lines configured by zsh-newuser-install

# vim config
export KEYTIMEOUT=10

### BASIC UNIVERSAL ALIASES AND SCRIPTS ###
# zsh stuff
alias edit_zsh='vim ~/.zshrc'
alias update_zsh='cd ~/.zprezto; git pull; cd -; zsh'
alias source_zsh='source ~/.zshrc'
alias zp='cd ~/.zprezto'

# aliasi niga
alias config='/usr/bin/git --git-dir=$HOME/.myconf/ --work-tree=$HOME'
alias ls='ls -GFh'

# boot up spacemacs in one fell swoop
spacemacs() {
    emacs --daemon
    emacsclient -t
}

# Quick utils

# Load remote workspace
start() {
  gcert
  ssh frazierk.mtv.corp.google.com
}

source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
